# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  build-image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: LS
          command: ls -la
      - docker/build:
          image: mm404/dokuwiki-webserver

workflows:
  assemble-dokuwiki-image:
    jobs:
      - build-image
