# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  build_image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: LS
          command: ls -la
      - run:
          name: Generate tag based on date
          command: echo "export TAG_NOW=\"$(date +%Y%m%d)\"" >> $BASH_ENV
      - run:
          name: Print TAG_NOW
          command: echo "TAG_NOW is $TAG_NOW"
      - docker/check
      - docker/build:
          image: mm404/dokuwiki-webserver
          tag: $TAG_NOW,latest
      - docker/push:
          image: mm404/dokuwiki-webserver
          tag: $TAG_NOW,latest
workflows:
  version: 2
  build_and_push:
    jobs:
      - build_image:
          filters:
            branches:
              only: main
